### ISSUE TITLE
AFS better separation between storage and business layer

### ISSUE THREAD

**Issue by geofjamg** [powsybl/powsybl-core#676]
There is design issues in AFS, related to storage and business layer separation. 
Here is a few examples:
 - We should not create file systems in config.yml but storage volumes and file systems (business object) rely on storage volume.
```yaml
mapdb-app-file-system:
        drive-name: test
        db-file: /storage/db
        remotely-accessible: true
```
should  be:
```yaml
mapdb-storage-volume:
        name: test
        db-file: /storage/db
        remotely-accessible: true
```
- `AppFileSystemProvider` should be `AppStorageProvider`
- A consequence is that MapDbAppFileSystem is totally useless class, just a constructor that forward to AppFileSystem. Same for any other ZZZZAppFileSystem.
- Everywhere in storage the rest API, we have 'fileSystemName', but file system in related to business part...
/rest/afs/v1/fileSystems/{fileSystemName}/nodes/{nodeId}
should be
/rest/afs/v1/volumes/{volumeName}/nodes/{nodeId}
 - Task management should be in a separate web service
